//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="GcSimulatorConfiguration")]
[System.Xml.Serialization.XmlRootAttribute("GcSimulatorConfiguration", Namespace="GcSimulatorConfiguration", IsNullable=false)]
public partial class GcSimulatorConfigurationType {
    
    private GcSimulatorConfigurationProbabilitiesType probabilitiesField;
    
    /// <remarks/>
    public GcSimulatorConfigurationProbabilitiesType Probabilities {
        get {
            return this.probabilitiesField;
        }
        set {
            this.probabilitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="GcSimulatorConfiguration")]
public partial class GcSimulatorConfigurationProbabilitiesType {
    
    private GcSimulatorConfigurationProbabilitiesEntryType[] itemsField;
    
    private GcSimulatorConfigurationProbabilitiesModeKindType modeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Entry")]
    public GcSimulatorConfigurationProbabilitiesEntryType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GcSimulatorConfigurationProbabilitiesModeKindType Mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="GcSimulatorConfiguration")]
public partial class GcSimulatorConfigurationProbabilitiesEntryType {
    
    private int stackDepthField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int StackDepth {
        get {
            return this.stackDepthField;
        }
        set {
            this.stackDepthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="GcSimulatorConfiguration")]
public enum GcSimulatorConfigurationProbabilitiesModeKindType {
    
    /// <remarks/>
    Flat,
    
    /// <remarks/>
    Override,
    
    /// <remarks/>
    Sequence,
}
